version: '3.7'
services:
  api:
    build: .
    image: pabloszx/gqty-examples-api
    restart: always
    ports:
      - 8090:8090
    environment:
      DATABASE_URL: ${DATABASE_URL}
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30 --cleanup
